Repository leapfrogtechnology/bulletin-board, pull requests merged in 2020-01, with the labels that each got.

#58 installation guide for bulletin board
  CONTRIBUTING.md
  INSTALL.md
  README.md
  logo_leapfrog.svg
Labels: Documentation, do not merge

#80 LE-273: Fix Being Mono Repo Husky and eslint not working
  api/.eslintrc
  api/.gitignore
  api/package.json
  api/src/middlewares/verifyGoogleToken.js
  api/src/services/authService.js
  api/src/services/userService.js
  api/yarn.lock
  app/package.json
  app/yarn.lock
  lerna.json
  package.json
  yarn.lock
Labels: bug fix, priority:high, refactor

#83 LE-274: Show User Image Instead of name in Bulletin dashboard
  app/src/components/dashboard/SideMenu.js
  app/src/components/moreMenu/index.js
  app/src/index.css
Labels: design

#85 LE-178: Fix the Bulletin Board UI Problems
  api/package.json
  app/package.json
  app/public/index.html
  app/src/assets/images/logout_icon.svg
  app/src/assets/images/screen_icon.svg
  app/src/assets/images/user_icon.svg
  app/src/assets/modalStyle.css.js
  app/src/components/addEntry/index.js
  app/src/components/bulletinScreen/styles.css
  app/src/components/dashboard/SideMenu.js
  app/src/components/editEntry/index.js
  app/src/components/listEntries/SortableItem.js
  app/src/components/login/index.js
  app/src/components/moreMenu/index.js
  app/src/index.css
Labels: design

#81 LE-241: Resolve Authentication Issue
  api/src/controllers/auth.js
  api/src/services/userService.js
  api/src/validators/userValidator.js
  app/src/components/dashboard/index.js
  app/src/components/login/index.js
  app/src/services/auth.js
Labels: bug fix

#84 LE-171: Add youtube playback feature in bulletin board
  app/src/components/addEntry/index.js
  app/src/components/bulletinScreen/index.js
  app/src/constants/regex.js
Labels: new feature

#82 LE-272: Fix secondary iframe autoplay in background
  app/src/components/addEntry/index.js
  app/src/components/bulletinScreen/index.js
  app/src/constants/regex.js
Labels: bug fix
